sudo: false
language: node_js
node_js:
- '8'
cache:
  directory:
  - node_modules
script: npm run lint
deploy:
  provider: heroku
  api_key:
    secure: KsQkzBLeVcmVMevRZaQLCAQ5lwtQIgJxtVBCPBNCpr75hesCUHWKkqnFx3gxSY09RyjkljJ05FpSHUF+pF5fitjk9QCZRGx5SwVXI7N+7BjMf9AayT2TkYhm4jVsodG6IlVdck3G4a5Wi/GiPTF1QtOsbL9zE6s+YbrXr7akWzPSoWHdgNyNZXnsVgOVDMOmkkNYYMzeObxe6oYSZ/p2XxOlNNNr4Cku8J1sD4SKyZIMvawLAfnZMbP59iZMSZ1Kn84rKKNzxhLGd9IY4FVuHByascylofH1eKxkf4g97mArpD5FUBjUNhNp6EwG5i3W6MjH5sIxBvJXeCSt6mwKIrfwX0WOZ3vHHEejyETl0dvjWp5AHmREhoSo7a8ObG23NDNkUp3ZmHBwUiYtFi7FjoaZQjroXW9/Com9MjteyUB9BHI82PRxxjjh8jr874+3D5JF5SuZsVDo7yZHXNaR1cnWnrfJygl2dV49l5SYA+U17yNhemz1Fh38LeHLC+XBhxcQd/LDNLxy4ftobG3pC/ws0jW17FCbpxkuZVyBwcBGHRMkQIwX1iUyQUq79+OBPZDyRUh7diyOEy4SCJKeU8zvzCD0uIr4whKalhpuHnlsE/RoMudjJeo5BKfZAGSRq6xay4A9cIdp5cCkvhp6B0wKoLiT+TyaGygVsB2DSJo=
